spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/spotify_users
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
jwt:
  secret: mysafeaccesskeymysafeaccesskeymysafe123
  refreshSecret: mysaferefreshkeymysaferefreshkey123
  expiration: 900000
  refreshExpiration: 604800000



