spring:
  application:
    name: Music Library Service
  datasource:
    url: jdbc:postgresql://localhost:5432/spotify_music
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      client:
        config:
          user-service: # must match @FeignClient(name="user-service")
            connectTimeout: 2000
            readTimeout: 2000
    compatibility-verifier:
      enabled: false

server:
  port: 8082

jwt:
  secret: mysafeaccesskeymysafeaccesskeymysafe123
  refreshSecret: mysaferefreshkeymysaferefreshkey123
  expiration: 900000
  refreshExpiration: 604800000

user:
  service:
    context-path: /users
  service-url: http://localhost:8081
